New york times article page clone
adejam/new-york-times-article-clone pull request #1
Opened 2020-04-02 19:01 UTC by adejam

# Project: NEW YORK TIMES ARTICLE PAGE CLONE
The main objective of this project is to build a clone of new york times article using Html and CSS.

The project uses semantic html and CSS positioning and floating elements. CSS flexbox in conjunction with CSS float property is used for effective positioning of the elements.

This project demonstrates usage of and CSS positioning techniques.

- [Assignment link](https://www.theodinproject.com/courses/html5-and-css3/lessons/positioning-and-floating-elements)

- [New york times article page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0)

- [Live Demo Link](https://adejam.github.io/new-york-times-article-clone/index.html)

2020-04-15 10:16 UTC, bolah2009 requested changes
Good job with the project!

Awesome that you making it even responsive... 

Kindly check the comment below and make changes accordingly.

I would also recommend checking this style guides for this and future projects:
- [CSS Style Guide](http://udacity.github.io/frontend-nanodegree-styleguide/css.html)
- [HTML Style Guide](http://udacity.github.io/frontend-nanodegree-styleguide/index.html)
- [Git Style Guide](https://udacity.github.io/git-styleguide/)

2020-04-15 10:16 UTC, bolah2009 commented on README.md
> +- NPM
You can use sublist for list like `CSS FLEXBOX` since it's under `CSS`. e.g
```md
- CSS
   - CSS Flexbox
   - CSS Media Quaries
```

2020-04-15 10:16 UTC, bolah2009 commented on stylesheet.css
> +  }
Avoid repeating yourself unnecessarily. And keep your code [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself). 
You can use the following instead:
```css
  .search_div,
  .category {
    display: none;
  }
```


Please do this for all occurrences.

2020-04-15 10:16 UTC, bolah2009 commented on stylesheet.css
> +  font-family: nyt-imperial, 'times new roman', times, serif;
Consider the following:
1. You have defined a `background` property, why are you defining another `background-color` property?
2. Unless you have `nyt-imperial` defined or imported it is useless here as the browser can't see it. See a list of available fonts here - https://www.w3schools.com/cssref/css_websafe_fonts.asp

2020-04-15 10:16 UTC, bolah2009 commented on stylesheet.css
> +  }
See previous comments

2020-04-15 10:16 UTC, bolah2009 commented on stylesheet.css
> +  }
Use shorthand for your `margin` property instead.

2020-04-15 10:16 UTC, bolah2009 commented on stylesheet.css
> +    line-height: calc(58px);
The `calc` function you using here is redundant. Is there a reason why you using this?

2020-04-15 10:16 UTC, bolah2009 commented on stylesheet.css
> +  }
See previous comments

2020-04-15 10:16 UTC, bolah2009 commented on stylesheet.css
> +  border-image: initial;
Is there a reason why you doing this, this property seems to be a default value already?
Make sure you are not declaring redundant CSS properties.

2020-04-15 10:16 UTC, bolah2009 commented on stylesheet.css
> +  border-color: rgb(102, 102, 102);
Use the shorthand here too instead. `border: width style color` will work equally.

2020-04-15 10:16 UTC, bolah2009 commented on stylesheet.css
> +  border-image: initial;
See previous comments

2020-04-19 09:07 UTC, adejam commented on README.md
> +- NPM
Thanks for the review. I will work on that.

2020-04-19 09:15 UTC, adejam commented on stylesheet.css
> +  font-family: nyt-imperial, 'times new roman', times, serif;
Thanks for the review. I'll work on this.

2020-04-19 09:19 UTC, adejam commented on stylesheet.css
> +  }
Thanks for the review. I'll adjust that.

2020-04-19 09:35 UTC, adejam commented on stylesheet.css
> +  border-image: initial;
Thanks for the review. I'll improve on that.

2020-04-19 10:22 UTC, adejam commented on stylesheet.css
> +  }
Thanks for the comment. I'll improve on that.

2020-04-22 10:12 UTC, bolah2009 approved these changes
It's a :+1: from me.

LGTM

2020-04-22 10:12 UTC, bolah2009 commented on README.md
> +- Linter
You are currently using `[stylint](https://stylelint.io/)`, it would be better to be more specific of what linter you are using.

2020-04-22 10:12 UTC, bolah2009 commented on README.md
> +- NPM
Try and link the meaning of `[NPM](https://www.npmjs.com/)` in case someone with no knowledge of it is reading the docs.

2020-04-22 10:12 UTC, bolah2009 commented on README.md
> +## Acknowledgments
You can add links to resources you used too here. Like the assignment link (Odin project), the page you cloned, the article you read to have the knowledge to build this site and also the assets (Icon, images, etc) you used.

2020-04-22 10:12 UTC, bolah2009 commented on index.html
> +</html>
This is not properly formatted. I would recommend using [prettier](https://prettier.io/) in future projects. Please let's discuss our to set this up in future projects.

2020-04-22 10:12 UTC, bolah2009 commented on stylesheet.css
> +body {
For future projects, I would recommend using **CSS imports**, see [here](https://developer.mozilla.org/en/docs/Web/CSS/@import) and [here](https://www.w3schools.com/cssref/pr_import_rule.asp) for more details. 

CSS imports help with code splitting, among other benefits, it makes your code more organised.

2020-04-22 12:35 UTC, adejam commented on README.md
> +- Linter
Thanks for the review. I'll work on this.

2020-04-22 12:36 UTC, adejam commented on README.md
> +- NPM
Thanks for the review. I'll improve on this.

2020-04-24 11:25 UTC, merged